
import asyncio
import sys
from pathlib import Path
from uuid import UUID
from sqlmodel import select

# Setup path
BACKEND_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_ROOT))

# Real IDs from database
GATEWAY_ID = UUID("1dd0bf21-5974-4080-b089-c832681cd1b4")
BOARD_ID = UUID("3cfb3a71-1844-4169-a732-1d23503b1c30")

async def main():
    from app.db.session import async_session_maker
    from app.models.tasks import Task
    from app.models.missions import Mission, MissionSubtask
    from app.services.missions.orchestrator import MissionOrchestrator
    from app.services.missions.status_machine import MISSION_STATUS_PENDING_APPROVAL
    from app.models.users import User

    async with async_session_maker() as session:
        # 1. Check/Create User for testing
        result = await session.exec(select(User))
        user = result.first()
        if not user:
            print("No user found for testing context.")
            return
        
        orchestrator = MissionOrchestrator(session)

        # 2. Create a Test Task
        print("Step 1: Creating a test task...")
        task = Task(
            title="[E2E Test] Deep Integration Test",
            description="Verify that Orchestrator can decompose and Sync Agent can receive tasks.",
            organization_id=user.active_organization_id,
            board_id=BOARD_ID,
            status="inbox",
            priority="urgent",
        )
        session.add(task)
        await session.commit()
        await session.refresh(task)
        print(f"Task created with ID: {task.id}")

        # 3. Create a Mission
        print("\nStep 2: Creating a mission...")
        mission = await orchestrator.create_mission(
            task_id=task.id,
            board_id=BOARD_ID,
            goal="Decompose this task into 2 simple subtasks: 1. Say hello, 2. Say goodbye. Assign them to RIQI Sync Agent.",
            approval_policy="auto",
        )
        print(f"Mission created with ID: {mission.id}, Initial Policy: {mission.approval_policy}")

        # 4. Dispatch Mission
        print("\nStep 3: Dispatching mission...")
        mission = await orchestrator.dispatch_mission(mission.id)
        print(f"Current status: {mission.status}")

        # 5. Handle Pending Approval if forced by policy
        if mission.status == MISSION_STATUS_PENDING_APPROVAL:
            print("Mission hit 'pending_approval' policy. Forcing approval to proceed with E2E...")
            # We mimic the logic in approve_mission endpoint
            from app.services.missions.status_machine import MISSION_STATUS_PENDING, ensure_mission_transition
            from app.core.time import utcnow
            ensure_mission_transition(mission.status, MISSION_STATUS_PENDING)
            mission.status = MISSION_STATUS_PENDING
            mission.approval_policy = "auto"
            mission.updated_at = utcnow()
            session.add(mission)
            await session.commit()
            print("Approval granted. Re-dispatching...")
            mission = await orchestrator.dispatch_mission(mission.id)
            print(f"Final Dispatch status: {mission.status}")

        # 6. Wait and check for Subtasks (Decomposition can take time because it calls LLM via Gateway)
        print("\nStep 4: Waiting for Orchestrator to decompose task (This calls LLM, waiting 15 seconds)...")
        await asyncio.sleep(15)
        
        # Refresh session to see background changes if any (though orchestrator.py writes them in dispatch)
        result = await session.exec(
            select(MissionSubtask).where(MissionSubtask.mission_id == mission.id)
        )
        subtasks = result.all()
        print(f"Found {len(subtasks)} subtasks generated by Orchestrator.")
        for i, st in enumerate(subtasks):
            print(f"  Subtask {i+1}: {st.label} (Status: {st.status}, Assigned: {st.assigned_subagent_id})")

        if len(subtasks) > 0:
            print("\n✅ SUCCESS: All systems integrated correctly. Mission reached decomposition phase.")
        else:
            print("\n❌ FAILED: No subtasks generated. Orchestrator Agent might have failed to respond.")

if __name__ == "__main__":
    asyncio.run(main())
