"""Mission task decomposition service."""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from app.models.missions import Mission
from app.services.openclaw.context.loader import ContextChunk
from app.services.openclaw.decomposer.templates import build_decompose_prompt
from app.services.openclaw.decomposer.validator import validate_subtasks
from app.services.openclaw.llm_client import LLMClient


@dataclass(slots=True)
class SubtaskSpec:
    """Structured decomposition item."""

    label: str
    description: str
    tool_scope: list[str]
    expected_output: str
    order: int


class TaskDecomposer:
    """Creates subtasks from mission goal and loaded context."""

    def __init__(self) -> None:
        self._llm_client = LLMClient()

    def _fallback_subtasks(
        self, *, mission: Mission, context: list[ContextChunk]
    ) -> list[dict[str, Any]]:
        context_desc = f"Review {len(context)} context chunks and extract facts."
        if not context:
            context_desc = "No context provided; identify assumptions and missing inputs."
        return [
            {
                "label": "Gather Facts",
                "description": context_desc,
                "tool_scope": ["context_loader", "analysis"],
                "expected_output": "A concise list of confirmed facts and unknowns.",
            },
            {
                "label": "Analyze Options",
                "description": f"Analyze tradeoffs to satisfy goal: {mission.goal[:220]}",
                "tool_scope": ["analysis"],
                "expected_output": "Recommendation with risks and confidence.",
            },
            {
                "label": "Prepare Execution Plan",
                "description": "Draft actionable next steps with owners and sequencing.",
                "tool_scope": ["analysis"],
                "expected_output": "Ordered execution checklist with dependencies.",
            },
            {
                "label": "Execute",
                "description": f"Execute the plan to achieve the goal: {mission.goal[:200]}",
                "tool_scope": ["context_loader", "http_requests", "file_operations", "analysis"],
                "expected_output": "Actual output/content generated by executing the plan.",
            },
        ]

    def _parse_llm_subtasks(self, raw: str) -> list[dict[str, Any]]:
        parsed = json.loads(raw)
        if isinstance(parsed, list):
            return [item for item in parsed if isinstance(item, dict)]
        if isinstance(parsed, dict):
            subtasks = parsed.get("subtasks")
            if isinstance(subtasks, list):
                return [item for item in subtasks if isinstance(item, dict)]
        raise ValueError("Unsupported LLM subtask payload format.")

    async def decompose(
        self, *, mission: Mission, context: list[ContextChunk]
    ) -> list[SubtaskSpec]:
        candidate: list[dict[str, Any]] = self._fallback_subtasks(mission=mission, context=context)
        if self._llm_client.is_enabled():
            prompt = build_decompose_prompt(mission=mission, context=context)
            try:
                llm_response = await self._llm_client.request(prompt)
                candidate = self._parse_llm_subtasks(llm_response.content)
            except Exception:
                candidate = self._fallback_subtasks(mission=mission, context=context)

        valid = validate_subtasks(candidate)
        if not valid:
            valid = validate_subtasks(self._fallback_subtasks(mission=mission, context=context))

        return [
            SubtaskSpec(
                label=str(item["label"]),
                description=str(item["description"]),
                tool_scope=list(item.get("tool_scope", [])),
                expected_output=str(item.get("expected_output", "")),
                order=index,
            )
            for index, item in enumerate(valid)
        ]
