"""Add system_role to Agent model

Revision ID: 85ef1026071d
Revises: fab24355b904
Create Date: 2026-03-14 11:36:11.045773

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '85ef1026071d'
down_revision = 'fab24355b904'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('system_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_agents_system_role'), 'agents', ['system_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_system_role'), table_name='agents')
    op.drop_column('agents', 'system_role')
    # ### end Alembic commands ###
