"""add approval rules table

Revision ID: d1a052a26d80
Revises: 2b3681a6dacd
Create Date: 2026-03-14 00:45:37.356217

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd1a052a26d80'
down_revision = '2b3681a6dacd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger_on_high_risk', sa.Boolean(), nullable=False),
    sa.Column('trigger_on_tool_usage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger_on_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('override_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_rules_organization_id'), 'approval_rules', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_rules_organization_id'), table_name='approval_rules')
    op.drop_table('approval_rules')
    # ### end Alembic commands ###
